services:
  gateway:
    build:
      context: ./services
      dockerfile: ../Dockerfile
    entrypoint: /opt/gateway
    restart: on-failure
    networks:
      - ds
    environment:
      - LIBRARY_ADDRESS=http://library
      - RATING_ADDRESS=http://rating
      - RESERVATION_ADDRESS=http://reservation
      - PORT=80
    ports:
      - "8080:80"

  reservation-postgres:
    image: library/postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    networks:
      - ds

  reservation:
    build:
      context: ./services
      dockerfile: ../Dockerfile
    entrypoint: /opt/reservation
    restart: on-failure
    networks:
      - ds
    environment:
      - PGHOST=reservation-postgres
      - PGPORT=5432
      - PGUSER=program
      - PGPASSWORD=test
      - PGDB=postgres
      - PGSSL=false
      - PORT=80
    ports:
      - "8070:80"

  library-postgres:
    image: library/postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    networks:
      - ds

  library:
    build:
      context: ./services
      dockerfile: ../Dockerfile
    entrypoint: /opt/library
    restart: on-failure
    networks:
      - ds
    environment:
      - PGHOST=library-postgres
      - PGPORT=5432
      - PGUSER=program
      - PGPASSWORD=test
      - PGDB=postgres
      - PGSSL=false
      - PORT=80
    ports:
      - "8060:80"

  rating-postgres:
    image: library/postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    networks:
      - ds

  rating:
    build:
      context: ./services
      dockerfile: ../Dockerfile
    entrypoint: /opt/rating
    restart: on-failure
    networks:
      - ds
    environment:
      - PGHOST=rating-postgres
      - PGPORT=5432
      - PGUSER=program
      - PGPASSWORD=test
      - PGDB=postgres
      - PGSSL=false
      - PORT=80
    ports:
      - "8050:80"

networks:
  ds:
    driver: bridge