name: service
namespace: avknyazhev

replicaCount: 1

image:
  repository: ghcr.io/muhomorfus/ds-lab-04
  tag: latest

postgresql:
  host: 127.0.0.1
  port: 5432
  user: program
  password: test
  db: persons
  sslEnabled: true

services:
  library: http://library
  rating: http://rating
  reservation: http://reservation

port: 80